In [0]:
# problem 22 Using names.txt (right click and 'Save Link/Target As...'), a 46K text file containing over five-thousand first names, 
#begin by sorting it into alphabetical order. Then working out the alphabetical value for each name, multiply this value by its alphabetical position in the list to obtain a name score.

#For example, when the list is sorted into alphabetical order, COLIN, 
#which is worth 3 + 15 + 12 + 9 + 14 = 53, is the 938th name in the list. So, COLIN would obtain a score of 938 Ã— 53 = 49714.

#What is the total of all the name scores in the file?

In [0]:
scoredict = {
    'A' : 1,    'B' : 2,    'C' : 3,    'D' : 4,
    'E' : 5,    'F' : 6,    'G' : 7,    'H' : 8,
    'I' : 9,    'J' : 10,    'K' : 11,    'L' : 12,
    'M' : 13,    'N' : 14,    'O' : 15,    'P' : 16,
    'Q' : 17,    'R' : 18,    'S' : 19,    'T' : 20,
    'U' : 21,    'V' : 22,    'W' : 23,    'X' : 24,
    'Y' : 25,    'Z' : 26,
    }
def namescore(name):
    name = name[1:len(name)-1]
    name = list(name)
    score = 0
    for i in name:
        score += scoredict[i]
    return score

file = open("problem 22 names.txt" , 'r')
data = file.read()
names = data.split(",")
names.sort()
result = 0
for index in range(len(names)):
    result += namescore(names[index])*(index+1)
print(result)
file.close()

871198282